task_name: SDCD2fmri

data:
  n_sub: 10
  train_batch_size: 64
  test_batch_size: 5
  input_step: 5
  pred_step: 1

sota:
  ST_CD:
    n_nodes: 50
    input_step: 5
    data_dim: 1
    total_epoch: 18
    batch_size: 64

    decoder:
      lr_dec: 1e-2
      pred_step: 1
      mlp_hid: 64
      gru_layers: 1
      shared_weights_decoder: false
      concat_h: true
      weight_decay: 1e-4
      prob: true

    encoder:
      hid_dim: 64
      lambda_1: 1e-1
      lr_enc: 1e-3