task_name: MGDCD2Lotka

data:
  n_sub: 3
  n_nodes: 20
  train_batch_size: 64
  test_batch_size: 64
  input_step: 2
  pred_step: 1
  train_start: 0
  train_end: 0
  test_start: 0
  test_end: 0

sota:
  ST_MSCD:
    n_nodes: 20
    n_sub: 3
    input_step: 2
    data_dim: 1
    total_epoch: 100
    batch_size: 64

    decoder:
      lr_dec: 1e-2
      model: multi_lstm
      pred_step: 1
      mlp_hid: 64
      gru_layers: 1
      shared_weights_decoder: false
      concat_h: true
      weight_decay: 1e-5
      prob: true

    encoder:
      hid_dim: 64
      lambda_1: 5e-2
      lambda_2: 1e-4
      lambda_3: 1e-4
      lr_enc: 1e-1